export const productData =  {
  columns: [
  // { key: 'productId', label: 'ID', sortable: true, isDate: false },
  { key: 'productName', label: 'Product Name', hidden: undefined, sortable: true, filterable: true, isDate: false},
  { key: 'catalogue', label: 'catalogue No', hidden: undefined, sortable: true, isDate: false },
  { key: 'companyName', label: 'Company Name', hidden: undefined, filterable: true, isDate: false },
  { key: 'quantity', label: 'Quantity', hidden: undefined, sortable: true, isDate: false },
  { key: 'priority', label: 'Priority', hidden: undefined, filterable: true, isDate: false },
  { key: 'received', label: 'Received', hidden: undefined, sortable: true, filterable: true, isDate: false },
  { key: 'remark', label: 'Remarks', hidden: undefined, sortable: true, isDate: false },
  { key: 'expiryDate', label: 'Expiry Date', hidden: undefined, filterable: true, isDate: true },
  { key: 'createdAt', label: 'Date of Entry', hidden: undefined, filterable: true, isDate: true },
],
list:[
  {
    "productId": 1,
    "productName": "Acetone",
    "catalogue": "AC123",
    "companyName": "Sigma-Aldrich",
    "quantity": 5,
    "priority": "High",
    "received": "Yes",
    "remark": "Store in a cool, dry place",
    "expiryDate": "2025-06-15T00:00:00.000Z",
    "createdAt": "2024-12-01T10:30:00.000Z"
  },
  {
    "productId": 2,
    "productName": "Ethanol",
    "catalogue": "ET234",
    "companyName": "Merck",
    "quantity": 20,
    "priority": "Medium",
    "received": "No",
    "remark": "Handle with care; flammable",
    "expiryDate": "2026-03-12T00:00:00.000Z",
    "createdAt": "2024-12-02T12:45:00.000Z"
  },
  {
    "productId": 3,
    "productName": "Sulfuric Acid",
    "catalogue": "SA345",
    "companyName": "Thermo Fisher",
    "quantity": 2,
    "priority": "Critical",
    "received": "Yes",
    "remark": "Corrosive; use proper PPE",
    "expiryDate": "2025-09-01T00:00:00.000Z",
    "createdAt": "2024-12-03T09:15:00.000Z"
  },
  {
    "productId": 4,
    "productName": "Sodium Chloride",
    "catalogue": "SC456",
    "companyName": "Fisher Scientific",
    "quantity": 50,
    "priority": "Low",
    "received": "Yes",
    "remark": "Common laboratory reagent",
    "expiryDate": "2027-01-10T00:00:00.000Z",
    "createdAt": "2024-12-04T14:20:00.000Z"
  },
  {
    "productId": 5,
    "productName": "Hydrogen Peroxide",
    "catalogue": "HP567",
    "companyName": "Sigma-Aldrich",
    "quantity": 10,
    "priority": "High",
    "received": "No",
    "remark": "Store away from light",
    "expiryDate": "2025-12-31T00:00:00.000Z",
    "createdAt": "2024-12-05T11:00:00.000Z"
  },
  {
    "productId": 6,
    "productName": "Potassium Permanganate",
    "catalogue": "KM678",
    "companyName": "Loba Chemie",
    "quantity": 7,
    "priority": "Medium",
    "received": "Yes",
    "remark": "Oxidizing agent; store safely",
    "expiryDate": "2025-08-20T00:00:00.000Z",
    "createdAt": "2024-12-06T16:10:00.000Z"
  },
  {
    "productId": 7,
    "productName": "Ammonium Nitrate",
    "catalogue": "AN789",
    "companyName": "Merck",
    "quantity": 15,
    "priority": "Critical",
    "received": "No",
    "remark": "Explosive risk; store securely",
    "expiryDate": "2025-11-15T00:00:00.000Z",
    "createdAt": "2024-12-07T08:00:00.000Z"
  },
  {
    "productId": 8,
    "productName": "Phosphoric Acid",
    "catalogue": "PA890",
    "companyName": "Thermo Fisher",
    "quantity": 3,
    "priority": "High",
    "received": "Yes",
    "remark": "Handle with care; corrosive",
    "expiryDate": "2026-07-25T00:00:00.000Z",
    "createdAt": "2024-12-08T09:30:00.000Z"
  },
  {
    "productId": 9,
    "productName": "Magnesium Sulfate",
    "catalogue": "MS901",
    "companyName": "Fisher Scientific",
    "quantity": 25,
    "priority": "Low",
    "received": "Yes",
    "remark": "Desiccant for drying",
    "expiryDate": "2026-04-15T00:00:00.000Z",
    "createdAt": "2024-12-09T15:40:00.000Z"
  },
  {
    "productId": 10,
    "productName": "Benzene",
    "catalogue": "BZ012",
    "companyName": "Loba Chemie",
    "quantity": 4,
    "priority": "Critical",
    "received": "No",
    "remark": "Highly flammable; carcinogenic",
    "expiryDate": "2025-02-18T00:00:00.000Z",
    "createdAt": "2024-12-10T14:00:00.000Z"
  }
],
pagination: {
  currentPage: 1,
  pageSize: 10,
  totalPages: 1,
  totalRecords: 0,
}
}

export const orderData = {
  columns: [
    // { key: 'orderId', label: 'ID', sortable: true, isDate: false },
    { key: 'productName', label: 'Product Name', sortable: true, filterable: true, isDate: false },
    { key: 'catalogue', label: 'catalogue No', sortable: true, isDate: false },
    { key: 'companyName', label: 'Company Name', filterable: true, isDate: false },
    { key: 'quantity', label: 'Quantity', sortable: true, isDate: false },
    { key: 'budget', label: 'Budget No', filterable: true, isDate: false },
    { key: 'price', label: 'Price', filterable: true, isDate: false },
    { key: 'remark', label: 'Remark', sortable: true, filterable: true, isDate: false },
    { key: 'status', label: 'Order Status', filterable: true, isDate: false },
    { key: 'attachment', label: 'Attach Files', filterable: true, isDate: false },
  ],
  list: [
    {
      orderId: 1,
      productName: "Acetone",
      catalogue: "AC123",
      companyName: "Sigma-Aldrich",
      price: 120,
      quantity: 10,
      budget: "BUDG123",
      remark: "Urgent requirement",
      status: "Pending Approval",
      attachment: "acetone_spec.pdf",
    },
    {
      orderId: 2,
      productName: "Ethanol",
      catalogue: "ET234",
      companyName: "Merck",
      price: 80,
      quantity: 25,
      budget: "BUDG124",
      remark: "For stock replenishment",
      status: "Approved",
      attachment: "",
    },
    {
      orderId: 3,
      productName: "Sulfuric Acid",
      catalogue: "SA345",
      companyName: "Thermo Fisher",
      price: 200,
      quantity: 5,
      budget: "BUDG125",
      remark: "Handle with care",
      status: "Pending Approval",
      attachment: "sulfuric_acid_msds.pdf",
    },
    {
      orderId: 4,
      productName: "Sodium Chloride",
      catalogue: "SC456",
      companyName: "Fisher Scientific",
      price: 50,
      quantity: 100,
      budget: "BUDG126",
      remark: "Common lab reagent",
      status: "Approved",
      attachment: "",
    },
    {
      orderId: 5,
      productName: "Hydrogen Peroxide",
      catalogue: "HP567",
      companyName: "Sigma-Aldrich",
      price: 150,
      quantity: 15,
      budget: "BUDG127",
      remark: "High priority",
      status: "Pending Approval",
      attachment: "",
    },
  ],
  pagination: {
    currentPage: 1,
    pageSize: 5,
    totalPages: 1,
    totalRecords: 5,
  },
};
