const UpdateOrderFormConfigFine = (budgetOptions: string[]) => [
  {
    id: "productName",
    label: "Product Name (Mandatory)",
    type: "text",
    validation: { required: true },
  },
  {
    id: "catalogue",
    label: "Catalogue (Mandatory)",
    type: "text",
    validation: { required: true },
  },
  {
    id: "companyName",
    label: "Company (Mandatory)",
    type: "text",
    validation: { required: true },
  },
  {
    id: "quantity",
    label: "Quantity (Mandatory)",
    type: "number",
    validation: { required: true },
  },
  {
    id: "expiryDate",
    label: "Expiry Date (Mandatory)",
    type: "date",
    validation: { required: true },
  },
  {
    id: "companyinternalno",
    label: "Company Internal No",
    type: "text",
    validation: { required: true },
  },
  {
    id: "sapmaterialno",
    label: "SAP Material No",
    type: "text",
    validation: { required: true },
  },
  {
    id: "weightvolsubqty",
    label: "Weight / Volume / Sub Qty",
    type: "text",
    validation: { required: true },
  },
  {
    id: "budgetno",
    label: "Budget No",
    type: "select",
    options: budgetOptions,
    validation: { required: true },
  },
  {
    id: "orderdate",
    label: "Order Date",
    type: "date",
    validation: { required: true },
  },
  // {
  //   id: "orderedby",
  //   label: "Ordered By",
  //   type: "text",
  //   validation: { required: true },
  // },
  {
    id: "concentration",
    label: "Concentration",
    type: "text",
    validation: { required: false },
  },
  {
    id: "price",
    label: "Price",
    type: "number",
    validation: { required: true },
  },
  {
    id: "casNumber",
    label: "CAS Number",
    type: "text",
    validation: { required: false },
  },
  {
    id: "hazardousSubstance",
    label: "Hazardous Substance",
    type: "select",
    options: ["Yes", "No"],
    validation: { required: false },
  },
  {
    id: "cmrSubstance",
    label: "CMR Substance",
    type: "select",
    options: ["Yes", "No"],
    validation: { required: false },
  },
  {
    id: "skinResorptive",
    label: "Skin Resorptive",
    type: "select",
    options: ["Yes", "No"],
    validation: { required: false },
  },
  {
    id: "ghsSymbols",
    label: "Select GHS Symbols",
    type: "checkbox-group",
    options: [
      "Explosive",
      "Flammable",
      "Oxidizing",
      "Corrosive",
      "Toxic",
      "Harmful",
      "Gas under pressure",
      "Environmental hazard",
    ],
    validation: { required: false },
  },
  {
    id: "ghsSignalWord",
    label: "Signal Word",
    type: "checkbox-group",
    options: ["Danger", "Attention"],
    validation: { required: true },
  },
  {
    id: "hPhrases",
    label: "GHS H-Phrases",
    type: "text",
    validation: { required: false },
  },
  {
    id: "pPhrases",
    label: "GHS P-Phrases",
    type: "text",
    validation: { required: false },
  },
  {
    id: "substitutionCheck",
    label: "Substitution Check Performed",
    type: "radio",
    options: ["Yes", "No"],
    validation: { required: true },
  },
  {
      id: "substitutionOption",
      label: "If No, specify the reason",
      type: "text",
      validation: { required: false },
      showIf: { field: "substitutionCheck", value: "No" },
  },
  {
      id: "substitutionOption",
      label: "If Yes, select one of the following",
      type: "select",
      options: [
      "Substance already substituted, by...",
      "Substance cannot be replaced, research chemical",
      "Substance cannot be replaced, it is necessary for the experiment",
      "Please complete the result of the test..."
      ],
      validation: { required: false },
      showIf: { field: "substitutionCheck", value: "Yes" },
  },
  {
    id: "storageLocation",
    label: "Storage Location",
    type: "text",
    validation: { required: false },
  },
  {
    id: "remarks",
    label: "Remarks",
    type: "text",
    validation: { required: false },
  },
  // {
  //   id: "inventoryType",
  //   label: "Inventory Type",
  //   type: "text",
  //   validation: { required: false },
  //   readOnly: true, // derived from context
  // },
  // {
  //   id: "status",
  //   label: "Status",
  //   type: "select",
  //   options: ["Pending", "Approved", "Rejected"],
  //   validation: { required: false },
  // },
  {
    id: "attachment",
    label: "Attachment",
    type: "file",
    validation: { required: false },
  },
  // {
  //   id: "safetydatasheet",
  //   label: "Safety Data Sheet (SDS)",
  //   type: "file",
  //   validation: { required: false },
  // },
];

export default UpdateOrderFormConfigFine;
