const updateProductFormConfig = (
  budgetOptions: string[],
  companyOptions: { label: string; key: string }[] = [],
  storageLocationOptions: string[] = [],
  hPhraseOptions: { label: string; key: string }[] = [],
  pPhraseOptions: { label: string; key: string }[] = [],
) => [
//   {
//     id: "productId",
//     label: "Product ID",
//     type: "number",
//     validation: { required: true },
//     readOnly: true, // ✅ Usually non-editable
//   },
  {
    id: "productname",
    label: "Product Name",
    type: "text",
    validation: { required: true },
  },
  {
    id: "catalogue",
    label: "Catalogue",
    type: "text",
    validation: { required: true },
  },
  {
    id: "companyname",
    label: "Company Name",
    type: "select",
    options: companyOptions,
    validation: { required: true },
  },
  {
    id: "quantity",
    label: "Quantity",
    type: "text",
    validation: {
      required: true,
      pattern: /^[0-9]+$/,
    },
  },
  {
    id: "expiryDate",
    label: "Expiry Date",
    type: "date",
    validation: { required: true },
  },
  {
    id: "companyInternalNo",
    label: "Company Internal No (auto-filled)",
    type: "text",
    validation: { required: false },
  },
  {
    id: "sapMaterialNo",
    label: "SAP Material No",
    type: "text",
    validation: { required: true },
  },
  {
    id: "wvsubqty",
    label: "W/V/Sub Qty",
    type: "text",
    validation: { required: true },
  },
  {
    id: "budgetno",
    label: "Budget No",
    type: "select",
    options: budgetOptions,
    validation: { required: true },
  },
  {
    id: "orderdate",
    label: "Order Date",
    type: "date",
    validation: { required: true },
  },
//   {
//     id: "orderedby",
//     label: "Ordered By",
//     type: "text",
//     validation: { required: true },
//   },
  {
    id: "concentration",
    label: "Concentration",
    type: "text",
    validation: { required: false },
  },
  {
    id: "price",
    label: "Price",
    type: "number",
    validation: {
      required: true,
      pattern: /^[0-9]+$/,
    },
  },
//   {
//     id: "amount",
//     label: "Amount",
//     type: "number",
//     validation: { required: true },
//   },
  {
    id: "remarks",
    label: "Remarks",
    type: "text",
    validation: { required: false },
  },
  {
    id: "casnumber",
    label: "CAS Number",
    type: "text",
    validation: { required: true },
  },
  {
    id: "hazardousSubstance",
    label: "Hazardous Substance",
    type: "select",
    options: ["Yes", "No"],
    validation: { required: true },
  },
  {
    id: "cmrSubstance",
    label: "CMR Substance",
    type: "select",
    options: ["Yes", "No"],
    validation: { required: true },
  },
  {
    id: "skinResorptive",
    label: "Skin Resorptive",
    type: "select",
    options: ["Yes", "No"],
    validation: { required: true },
  },
  {
    id: "ghsSymbols",
    label: "GHS Symbols",
    type: "checkbox-group",
    colSize: "col-12",
    options: [
      "Explosive",
      "Flammable",
      "Oxidizing",
      "Corrosive",
      "Toxic",
      "Harmful",
      "Gas under pressure",
      "Environmental hazard",
    ],
    validation: { required: false },
  },
  {
    id: "ghsSignalWord",
    label: "Signal Word",
    type: "checkbox-group",
    options: ["Danger", "Attention"],
    validation: { required: true },
  },
  {
    id: "hPhrases",
    label: "H-Phrases",
    type: "typeahead",
    options: hPhraseOptions,
    validation: { required: true },
  },
  {
    id: "pPhrases",
    label: "P-Phrases",
    type: "typeahead",
    options: pPhraseOptions,
    validation: { required: true },
  },
  {
    id: "substitutionCheck",
    label: "Substitution Check Performed",
    type: "select",
    options: ["Yes", "No"],
    validation: { required: true },
  },
  {
    id: "substitutionOption",
    label: "Substitution Option / Remark",
    type: "text",
    validation: { required: false },
  },
  {
    id: "storageLocation",
    label: "Storage Location",
    type: "select",
    options: storageLocationOptions,
    validation: { required: true },
  },
//   {
//     id: "groupName",
//     label: "Group Name",
//     type: "text",
//     validation: { required: true },
//     readOnly: true, // usually derived from user role
//   },
//   {
//     id: "priority",
//     label: "Priority",
//     type: "select",
//     options: ["Normal", "High", "Low"],
//     validation: { required: true },
//   },
//   {
//     id: "received",
//     label: "Received Status",
//     type: "select",
//     options: ["Pending", "Received", "Not Received"],
//     validation: { required: true },
//   },
//   {
//     id: "fileName",
//     label: "Attached File Name",
//     type: "text",
//     readOnly: true,
//   },
//   {
//     id: "fileType",
//     label: "File Type",
//     type: "text",
//     readOnly: true,
//   },
  {
    id: "applicationOfHazardousSubstance",
    label: "Application of the Hazardous Substance",
    type: "textarea",
    colSize: "col-12",
    validation: { required: false },
  },
  {
    id: "concentrationWorkingVolume",
    label: "Concentration / Working Volume",
    type: "text",
    validation: { required: false },
  },
  {
    id: "labNoWorkingWithChemical",
    label: "Lab No. Working with this Chemical",
    type: "text",
    validation: { required: false },
  },
  {
    id: "numberOfEmployees",
    label: "Number of Employees Working with this Chemical",
    type: "text",
    validation: { required: false },
  },
  {
    id: "handlingDurationGreater15Min",
    label: "Is Handling Duration Greater than 15min/day?",
    type: "select",
    options: ["Yes", "No"],
    validation: { required: false },
  },
  {
    id: "hazardousDueToSkinContact",
    label: "Hazardous Due to Skin Contact?",
    type: "select",
    options: ["Yes", "No"],
    validation: { required: false },
  },
  {
    id: "attachment",
    label: "Attachment",
    type: "file",
    validation: { required: false },
  },
];

export default updateProductFormConfig;
